application: union-car
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app

- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /
  static_dir: dist
